# Generated by Django 4.0.4 on 2022-04-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_options_alter_post_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
